version: '3.7'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 69MEXT123
      POSTGRES_DB: ilocos_sur_property_db  
    ports:
      - "5432:5432"
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL:"postgresql://postgres:69MEXT123@postgres:5432/ilocos_sur_property_db?schema=public" 
    networks:
      - prisma-network
    depends_on:
      postgres:
        condition: service_healthy
networks:
  prisma-network:
    driver: bridge
volumes:
  postgres_data: